version: '3.9'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binotify-premium-app
    ports:
      - "3000:3000"
    volumes:
      - "./:/app"
      - "./:/node_modules"